
GET http://localhost:8080/post

###

GET http://localhost:8080/post/1

###

POST http://localhost:8080/post
Content-type: application/json

{
    "titulo": "Programando para Backend",
    "texto": "Meu texto",
    "userId" : 1
}

###

PUT http://localhost:8080/post?id=1
Content-type: application/json

{
    "titulo": "Novo Título",
    "texto": "Novo texto"
}

###

DELETE http://localhost:8080/post?id=d1fa1cff-e519-4c11-bede-4d7ad192796a