
GET http://localhost:8080/api/post

###

GET http://localhost:8080/api/post/1

###

POST http://localhost:8080/api/posts
Content-Type: application/json
Authorization: Bearer 'Token'

{
    "titulo": "Programando em JS Backend",
    "texto": "Título do texto...",
    "userId": 3
}
###

PUT http://localhost:8080/api/post?id=1
Content-type: application/json

{
    "titulo": "Novo Título",
    "texto": "Novo texto"
}

###

DELETE http://localhost:8080/api/post?id=d1fa1cff-e519-4c11-bede-4d7ad192796a