GET http://localhost:8080

###

GET http://localhost:8080/api/usuario/7ea0bf3c-3541-4ad0-a2cc-e97654cc616e

###

GET http://localhost:8080/api/usuario

###

POST http://localhost:8080/api/usuario
Content-type: application/json

{
    "email": "tesla@gmail.com",
    "senha": "sadj1923"
}

###

PUT http://localhost:8080/api/usuario?id=ea706d20-3470-415e-ae34-5fa0c891eadd
Content-type: application/json

{
    "nome": "Thiago"
}

###

DELETE http://localhost:8080/api/usuario?id=2
